In [17]:
import pandas as pd
import time
import pymysql

from tqdm import tqdm
from clickhouse_driver import Client

tqdm.pandas()

pd.options.mode.chained_assignment = None

start_time = time.time()

path = r'D:\Отчеты\категории_номеров\suitecrm_robot_jc_robot_log.csv'

client_click = Client(host='192.168.1.99', port='9000', user='default', password='jdfwl6812hwe',
                database='suitecrm_robot_ch', settings={'use_numpy': True})

client_mysql = pymysql.Connect(host='192.168.1.128', user='base_dep_slave', passwd='QxPGHGdzCLao',
                             db="suitecrm",
                             charset='utf8')

sql = '''select uniqueid, phone, client_status, assigned_user_id
        from suitecrm_robot.jc_robot_log
        where date(call_date) >= '2023-01-01';
        '''

# df = pd.read_sql_query(sql, client_mysql)

# print(df.head())
# print(df.info())

df = pd.read_csv(path, sep=';', encoding='utf-8', low_memory=False, chunksize=1000000)

# print(df['uniqueid'].isna().sum())
# print(df['phone'].isna().sum())
# print(df['client_status'].isna().sum())
# print(df['assigned_user_id'].isna().sum())

# df = df.astype('object')

# client_click.insert_dataframe('INSERT INTO suitecrm_robot_ch.jc_robot_log_january_only VALUES',
#                             df[['uniqueid', 'phone', 'client_status', 'assigned_user_id']])

for chunk in df:
    print(chunk.head())
    print(chunk.info())
    chunk = chunk.astype('object')
    print(chunk.info())
    client_click.insert_dataframe('INSERT INTO suitecrm_robot_ch.jc_robot_log_january_only VALUES', chunk)

end_time = time.time()
print()
print(f'Ушло времени на все файлы: {round(end_time - start_time, 3)} сек.')
print('OK')

               uniqueid        phone client_status assigned_user_id  \
0    1673707842.86016.5  89850932726   null_status                1
1   1674117548.39466.25  89219056424   null_status                1
2    1675065357.18154.5  89089995677   null_status                1
3  1673440380.109127.35  89645575440   null_status                1
4   1674900246.52684.35  89274762534   null_status                1

   last_step  ochered            call_date                              ptv_c  \
0        261     9180  2023-01-14 14:50:43  ^10^,^22^,^11^,^3_o^,^5_o^,^19_o^
1        261     9214  2023-01-19 08:39:09                                NaN
2        102     9060  2023-01-30 07:55:58                              ^5_c^
3        261     9270  2023-01-11 12:33:02                  ^14^,^5_c^,^11_c^
4        111     9218  2023-01-28 10:04:07                             ^11_c^

   region_c
0         1
1         7
2         1
3         1
4         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998660 non-null   object
 3   assigned_user_id  998660 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             517700 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998660 non-null   object
 3   assigned_user_id  998660 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             517700 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
1000000    1674123094.44865.3  89082117474   null_status                1
1000001   1674802627.16572.33  89635314682   null_status                1
1000002   1674037907.71260.29  89251490851   null_status                1
1000003   1674632346.25972.28  89024812056   null_status                1
1000004  1672839515.109871.25  89038314811   null_status                1

         last_step  ochered            call_date  \
1000000        102     9170  2023-01-19 10:11:36
1000001          2     9200  2023-01-27 06:57:08
1000002        261     9017  2023-01-18 10:31:48
1000003          8     9004  2023-01-25 07:39:07
1000004        102     9255  2023-01-04 13:38:36

                                 ptv_c  region_c
1000000  ^10_19^,^5_19^,^3_19^,^11_19^         2
1000001                            NaN         5
1000002                 ^10_18^,^5_18^         6
1000003                          ^5_c^         2
1000004                          ^5_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 1000000 to 1999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998699 non-null   object
 3   assigned_user_id  998699 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519380 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 1000000 to 1999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998699 non-null   object
 3   assigned_user_id  998699 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519380 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
2000000   1673015143.130111.7  89005241838   null_status                1
2000001   1673538319.155493.7  89277105130   null_status                1
2000002    1673590525.7412.33  89294757555   null_status                1
2000003   1674027230.21732.26  89534313556   null_status                1
2000004  1674145385.160546.30  89788653712   null_status                1

         last_step  ochered            call_date  \
2000000        102     9077  2023-01-06 14:25:44
2000001        261     9289  2023-01-12 15:45:20
2000002         14     9030  2023-01-13 06:15:26
2000003        261     9100  2023-01-18 07:33:52
2000004          2     9291  2023-01-19 16:23:06

                                                     ptv_c  region_c
2000000                                             ^11_c^         2
2000001                                                NaN         7
2000002                                                NaN         2
2000003  ^10^,^5^,^11^,^6^,^3^,^10_18^,^5_18^,^6_18^,^3...         1
2000004                                                NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 2000000 to 2999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998700 non-null   object
 3   assigned_user_id  998700 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518909 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 2000000 to 2999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998700 non-null   object
 3   assigned_user_id  998700 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518909 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
3000000     1673849415.5383.5  89990574746   null_status                1
3000001   1674553979.35810.17  89146062348   null_status                1
3000002  1674235031.158545.35  89182541004           NaN              NaN
3000003    1674557850.60768.3  89952046443   null_status                1
3000004    1675141120.2055.30  89397791209   null_status                1

         last_step  ochered            call_date  \
3000000          2     9235  2023-01-16 06:10:16
3000001        261     9060  2023-01-24 09:53:01
3000002         10     9077  2023-01-20 17:17:12
3000003        111     9015  2023-01-24 10:57:33
3000004        261     9060  2023-01-31 04:58:41

                                 ptv_c  region_c
3000000              ^10^,^5^,^3^,^11^         1
3000001                            NaN         7
3000002                            NaN         0
3000003  ^5^,^3_o^,^6_o^,^11_o^,^10_o^         1
3000004                            NaN         7

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 3000000 to 3999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998740 non-null   object
 3   assigned_user_id  998740 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518433 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 3000000 to 3999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998740 non-null   object
 3   assigned_user_id  998740 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518433 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
4000000   1673513400.19333.20  89034367995   null_status                1
4000001  1673440252.107883.28  89289001269   null_status                1
4000002   1673082043.19336.32  89129144072   null_status                1
4000003   1675069159.44156.31  89066824416   null_status                1
4000004   1674552233.60370.34  89301653565   null_status                1

         last_step  ochered            call_date  \
4000000         10     9020  2023-01-12 08:50:01
4000001          2     9179  2023-01-11 12:30:54
4000002        250     9215  2023-01-07 09:00:44
4000003          8     9003  2023-01-30 08:59:20
4000004        111     9118  2023-01-24 09:23:54

                                                     ptv_c  region_c
4000000                              ^10_17^,^6_17^,^5_17^         2
4000001  ^10_16^,^5_16^,^6_16^,^11_16^,^10_18^,^5_18^,^...         4
4000002                                      ^11^,^5^,^19^         1
4000003                                                NaN         6
4000004                                  ^10^,^5^,^3^,^19^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 4000000 to 4999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998688 non-null   object
 3   assigned_user_id  998688 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             517944 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 4000000 to 4999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998688 non-null   object
 3   assigned_user_id  998688 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             517944 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                    uniqueid        phone client_status assigned_user_id  \
5000000     1673497015.947.3  89010173944   null_status                1
5000001   1674399471.72704.5  89147023448   null_status                1
5000002   1673874390.2559.21  89524240748   null_status                1
5000003  1673191347.48065.34  89222682715   null_status                1
5000004  1674303162.85202.26  89615074491   null_status                1

         last_step  ochered            call_date  ptv_c  region_c
5000000        106     9290  2023-01-12 04:16:55    NaN         7
5000001          2     9013  2023-01-22 14:57:52    NaN         7
5000002        102     9255  2023-01-16 13:06:31    NaN         5
5000003         10     9077  2023-01-08 15:22:28  ^5_c^         2
5000004        250     9291  2023-01-21 12:12:43    NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 5000000 to 5999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998748 non-null   object
 3   assigned_user_id  998748 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518673 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 5000000 to 5999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998748 non-null   object
 3   assigned_user_id  998748 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518673 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
6000000   1674200716.23973.32  89153765911   null_status                1
6000001  1673274293.129173.33  89539888390   null_status                1
6000002   1673686365.30048.35  89809209306   null_status                1
6000003    1674998792.70721.5  89778080016   null_status                1
6000004     1673538129.998.24  89102681299   null_status                1

         last_step  ochered            call_date           ptv_c  region_c
6000000          2     9090  2023-01-20 07:45:18             NaN         6
6000001          2     9270  2023-01-09 14:24:54   ^19_c^,^11_c^         1
6000002          2     9234  2023-01-14 08:52:46             NaN         7
6000003        102     9270  2023-01-29 13:26:33             NaN         2
6000004        102     9131  2023-01-12 15:42:10  ^5_15^,^19_15^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 6000000 to 6999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998721 non-null   object
 3   assigned_user_id  998721 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518695 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 6000000 to 6999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998721 non-null   object
 3   assigned_user_id  998721 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518695 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None

                     uniqueid        phone client_status assigned_user_id  \
7000000   1673335105.16460.32  89618461385   null_status                1
7000001  1674047376.113499.26  89023641972   null_status                1
7000002    1673951884.75421.6  89188697505   null_status                1
7000003   1674055188.148268.6  89814524816   null_status                1
7000004    1673340510.40600.6  89506092886   null_status                1

         last_step  ochered            call_date  \
7000000        261     9290  2023-01-10 07:18:25
7000001         98     9170  2023-01-18 13:09:37
7000002          2     9170  2023-01-17 10:38:06
7000003          8     9004  2023-01-18 15:19:49
7000004        261     9140  2023-01-10 08:48:31

                                                 ptv_c  region_c
7000000                                         ^11_c^         7
7000001  ^10_16^,^11_16^,^5_15^,^3_15^,^10_21^,^10_18^         2
7000002                                 ^5_16^,^11_16^         2
7000003                                            NaN         6
7000004                              ^10^,^5^,^3^,^11^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 7000000 to 7999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998726 non-null   object
 3   assigned_user_id  998726 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519575 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 7000000 to 7999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998726 non-null   object
 3   assigned_user_id  998726 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519575 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
8000000   1674477294.98704.33  89221620168   null_status                1
8000001  1673361144.141623.33  89277419194   null_status                1
8000002  1675086964.124525.29  89588592520   null_status                1
8000003  1674478145.102228.29  89811563246   null_status                1
8000004  1673534507.141549.28  89527799590   null_status                1

         last_step  ochered            call_date              ptv_c  region_c
8000000        106     9234  2023-01-23 12:34:55                NaN         7
8000001          2     9289  2023-01-10 14:32:25                NaN         7
8000002        261     9002  2023-01-30 13:56:05                NaN         6
8000003        102     9028  2023-01-23 12:49:06  ^10^,^5^,^6^,^19^         1
8000004          2     9157  2023-01-12 14:41:48     ^5_18^,^11_18^         5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 8000000 to 8999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998689 non-null   object
 3   assigned_user_id  998689 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519370 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 8000000 to 8999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998689 non-null   object
 3   assigned_user_id  998689 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519370 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                    uniqueid        phone client_status assigned_user_id  \
9000000  1673085791.30793.33  89097061728   null_status                1
9000001   1674034463.55356.7  89504248888   null_status                1
9000002  1674388859.66737.31  89381088317   null_status                1
9000003   1675081963.6889.21  89000722778   null_status                1
9000004   1674278823.2444.33  89199336718   null_status                1

         last_step  ochered            call_date        ptv_c  region_c
9000000        250     9215  2023-01-07 10:03:12       ^11_c^         7
9000001        106     9027  2023-01-18 09:34:24  ^6_c^,^5_c^         1
9000002        102     9077  2023-01-22 12:01:00           ^^         1
9000003          1     9004  2023-01-30 12:32:44          NaN         6
9000004        250     9234  2023-01-21 05:27:04          NaN         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 9000000 to 9999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998679 non-null   object
 3   assigned_user_id  998679 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518995 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 9000000 to 9999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998679 non-null   object
 3   assigned_user_id  998679 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518995 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
10000000   1675163493.81512.36  89188912264   null_status                1
10000001   1675155958.48706.29  89295832093   null_status                1
10000002  1673620825.138663.26  89626172561   null_status                1
10000003  1674831214.138189.28  89185166615   null_status                1
10000004    1673588965.4759.31  89147983229   null_status                1

          last_step  ochered            call_date  \
10000000        102     9009  2023-01-31 11:11:34
10000001        261     9059  2023-01-31 09:05:59
10000002        102     9077  2023-01-13 14:40:27
10000003        261     9029  2023-01-27 14:53:35
10000004        261     9030  2023-01-13 05:49:26

                                                      ptv_c  region_c
10000000                                                NaN         6
10000001                                                NaN         6
10000002                                ^11_c^,^6_c^,^11_c^         2
10000003  ^10^,^5^,^11^,^3^,^10_18^,^6_18^,^3_18^,^11_18...         1
10000004                                                NaN         7

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 10000000 to 10999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998651 non-null   object
 3   assigned_user_id  998651 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518562 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 10000000 to 10999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998651 non-null   object
 3   assigned_user_id  998651 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518562 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status  \
11000000  1674316349.134011.31  89376474988      refusing
11000001    1673850185.9607.26  89836228105   null_status
11000002   1674395760.94254.35  89883994939   null_status
11000003    1673619658.8310.24  89775071536   null_status
11000004  1673019125.146524.31  89114849306   null_status

                              assigned_user_id  last_step  ochered  \
11000000  f5b007d6-e414-ca86-d026-61c56b00e4fc         91     9004
11000001                                     1        250     9290
11000002                                     1        261     9162
11000003                                     1        261     9090
11000004                                     1          2     9020

                    call_date          ptv_c  region_c
11000000  2023-01-21 15:52:30            ^5^         1
11000001  2023-01-16 06:23:06            NaN         7
11000002  2023-01-22 13:56:01  ^10^,^5^,^11^         1
11000003  2023-01-13 14:20:59         ^11_c^         7
11000004  2023-01-06 15:32:06            NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 11000000 to 11999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998686 non-null   object
 3   assigned_user_id  998686 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519292 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 11000000 to 11999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998686 non-null   object
 3   assigned_user_id  998686 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519292 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
12000000  1672831224.73801.25  89058262788   null_status                1
12000001   1673430314.42247.5  89298584022   null_status                1
12000002  1674563052.10310.22  89053534057   null_status                1
12000003   1673427833.48685.6  89247669639   null_status                1
12000004   1675152937.24904.4  89629934648   null_status                1

          last_step  ochered            call_date         ptv_c  region_c
12000000          2     9234  2023-01-04 11:20:25           NaN         6
12000001         10     9291  2023-01-11 09:45:16           NaN         7
12000002        106     9202  2023-01-24 12:24:13  ^11_c^,^5_c^         1
12000003         10     9060  2023-01-11 09:03:55           NaN         7
12000004        102     9090  2023-01-31 08:15:37           NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 12000000 to 12999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998691 non-null   object
 3   assigned_user_id  998691 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518555 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 12000000 to 12999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998691 non-null   object
 3   assigned_user_id  998691 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518555 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
13000000  1674298871.15133.18  89284043395   null_status                1
13000001   1674300854.53390.5  89263724643   null_status                1
13000002  1673279534.148691.6  89995321598   null_status                1
13000003  1674305654.95556.36  89888668023   null_status                1
13000004  1674998417.99072.35  89219248336   null_status                1

          last_step  ochered            call_date ptv_c  region_c
13000000         10     9291  2023-01-21 11:01:12   NaN         6
13000001          2     9059  2023-01-21 11:34:15   NaN         6
13000002        250     9214  2023-01-09 15:52:15   NaN         6
13000003        102     9291  2023-01-21 12:54:15   NaN         6
13000004        111     9204  2023-01-29 13:20:18   NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 13000000 to 13999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998709 non-null   object
 3   assigned_user_id  998709 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519205 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 13000000 to 13999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998709 non-null   object
 3   assigned_user_id  998709 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519205 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None

                     uniqueid        phone client_status assigned_user_id  \
14000000   1674886016.4914.29  89397026205   null_status                1
14000001   1674210122.2645.15  89242011445   null_status                1
14000002  1673191081.151631.6  89063864454   null_status                1
14000003    1673870700.588.18  89132827412   null_status                1
14000004  1674730262.50030.28  89678502971   null_status                1

          last_step  ochered            call_date         ptv_c  region_c
14000000        109     9004  2023-01-28 06:06:57           ^5^         1
14000001          8     9004  2023-01-20 10:22:03           NaN         5
14000002        102     9059  2023-01-08 15:18:02           NaN         6
14000003          2     9196  2023-01-16 12:05:02  ^5^,^6^,^11^         1
14000004        261     9077  2023-01-26 10:51:03  ^11_c^,^5_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 14000000 to 14999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998684 non-null   object
 3   assigned_user_id  998684 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519416 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 14000000 to 14999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998684 non-null   object
 3   assigned_user_id  998684 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519416 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
15000000  1673598056.35341.35  89619638948   null_status                1
15000001  1675070060.47708.32  89841390846   null_status                1
15000002  1673701549.98282.29  89123841867   null_status                1
15000003   1674465523.32011.3  89261818951   null_status                1
15000004   1674637107.3582.20  89199362890   null_status                1

          last_step  ochered            call_date              ptv_c  region_c
15000000        109     9030  2023-01-13 08:20:57                NaN         5
15000001          2     9030  2023-01-30 09:14:21                NaN         6
15000002          2     9029  2023-01-14 13:05:50  ^10^,^5^,^3^,^11^         1
15000003        111     9090  2023-01-23 09:18:44                NaN         6
15000004        102     9170  2023-01-25 08:58:28  ^10^,^5^,^3^,^11^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 15000000 to 15999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998739 non-null   object
 3   assigned_user_id  998739 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518943 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 15000000 to 15999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998739 non-null   object
 3   assigned_user_id  998739 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518943 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
16000000    1675163666.57146.5  89009473683   null_status                1
16000001    1674828142.86911.4  89274929983   null_status                1
16000002    1674130283.7137.24  89539745642   null_status                1
16000003  1674712382.1394098.1  89039863377   null_status                1
16000004    1674710453.7422.25  89246800014   null_status                1

          last_step  ochered            call_date                      ptv_c  \
16000000        261     9050  2023-01-31 11:14:27                        NaN
16000001        261     9218  2023-01-27 14:02:23                        NaN
16000002         10     9270  2023-01-19 12:11:24                      ^5_c^
16000003          2     9201  2023-01-26 05:53:03                    ^5^,^3^
16000004        261     9100  2023-01-26 05:20:54  ^5^,^6^,^11^,^6_c^,^11_c^

          region_c
16000000         2
16000001         6
16000002         2
16000003         1
16000004         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 16000000 to 16999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519958 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 16000000 to 16999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519958 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status  \
17000000   1675078796.87527.34  89134652341      refusing
17000001   1673440304.76316.21  89923508018   null_status
17000002  1674148539.168008.31  89035699058   null_status
17000003  1673439158.102296.26  89523827214   null_status
17000004   1674630283.16797.29  89647697233   null_status

                              assigned_user_id  last_step  ochered  \
17000000  1e8b7a6a-c63b-648b-fbbf-639aca2f64e1         81     9100
17000001                                     1         10     9131
17000002                                     1        261     9059
17000003                                     1        261     9214
17000004                                     1        261     9090

                    call_date                   ptv_c  region_c
17000000  2023-01-30 11:39:58        ^5^,^6^,^3^,^11^         1
17000001  2023-01-11 12:31:45  ^5^,^19^,^19_c^,^11_c^         1
17000002  2023-01-19 17:15:40            ^5_c^,^11_c^         2
17000003  2023-01-11 12:12:40                     NaN         6
17000004  2023-01-25 07:04:44                     NaN         6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 17000000 to 17999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998650 non-null   object
 3   assigned_user_id  998650 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519339 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 17000000 to 17999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998650 non-null   object
 3   assigned_user_id  998650 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519339 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
18000000    1673621810.99542.3  89254620623   null_status                1
18000001   1674551330.56292.31  89827414669   null_status                1
18000002    1673870304.3511.24  89189062600   null_status                1
18000003  1674133852.114643.29  89198780101   null_status                1
18000004    1674471829.51537.5  89236448632   null_status                1

          last_step  ochered            call_date  \
18000000        250     9118  2023-01-13 14:56:51
18000001        261     9297  2023-01-24 09:08:51
18000002        261     9169  2023-01-16 11:58:25
18000003        261     9077  2023-01-19 13:10:53
18000004        102     9050  2023-01-23 11:03:50

                                 ptv_c  region_c
18000000  ^10^,^5^,^14^,^22^,^11^,^19^         1
18000001                      ^5^,^11^         1
18000002                 ^11^,^10^,^5^         1
18000003                  ^11_c^,^5_c^         1
18000004                  ^11_c^,^5_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 18000000 to 18999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998693 non-null   object
 3   assigned_user_id  998693 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518648 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 18000000 to 18999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998693 non-null   object
 3   assigned_user_id  998693 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518648 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
19000000    1673617164.2438.18  89275222771   null_status                1
19000001  1673707272.121042.31  89003668152   null_status                1
19000002  1673874602.111793.34  89045254498   null_status                1
19000003    1674898656.32057.5  89504801710   null_status                1
19000004   1674553524.67252.25  89501193450   null_status                1

          last_step  ochered            call_date  \
19000000        261     9077  2023-01-13 13:39:25
19000001        261     9050  2023-01-14 14:41:13
19000002          2     9255  2023-01-16 13:10:03
19000003        261     9234  2023-01-28 09:37:37
19000004        261     9290  2023-01-24 09:45:26

                                                      ptv_c  region_c
19000000  ^3_o^,^6_o^,^11_o^,^19_o^,^10_o^,^11_c^,^11_c^...         2
19000001                           ^10^,^5^,^6^,^6_o^,^5_o^         1
19000002                                                NaN         4
19000003                                                NaN         7
19000004                                                NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 19000000 to 19999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998648 non-null   object
 3   assigned_user_id  998648 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519414 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 19000000 to 19999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998648 non-null   object
 3   assigned_user_id  998648 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519414 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
20000000   1673451295.115691.3  89102493252   null_status                1
20000001   1673109947.101969.3  89183054755   null_status                1
20000002   1674128973.90940.25  89956040697   null_status                1
20000003  1675087145.125769.30  89630034283   null_status                1
20000004    1673422788.1898.16  89006201089   null_status                1

          last_step  ochered            call_date                 ptv_c  \
20000000        209     9062  2023-01-11 15:34:56  ^5_18^,^11_18^,^_18^
20000001          2     9291  2023-01-07 16:45:49                   NaN
20000002        111     9096  2023-01-19 11:49:34            ^3^,^5_18^
20000003          8     9004  2023-01-30 13:59:06                   NaN
20000004        261     9096  2023-01-11 07:39:49                   ^3^

          region_c
20000000         4
20000001         5
20000002         1
20000003         5
20000004         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 20000000 to 20999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998667 non-null   object
 3   assigned_user_id  998667 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519209 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 20000000 to 20999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998667 non-null   object
 3   assigned_user_id  998667 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519209 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
21000000   1674640516.61538.36  89144217337   null_status                1
21000001     1674373028.7566.4  89196705355   null_status                1
21000002   1673609570.88196.35  89505521344   null_status                1
21000003  1673271695.117942.31  89282798941   null_status                1
21000004   1675092359.148232.6  89012894750   null_status                1

          last_step  ochered            call_date  \
21000000        261     9060  2023-01-25 09:55:17
21000001          2     9204  2023-01-22 07:37:08
21000002        102     9212  2023-01-13 11:32:51
21000003        102     9179  2023-01-09 13:41:36
21000004        102     9003  2023-01-30 15:26:00

                                                      ptv_c  region_c
21000000                                        ^6_c^,^5_c^         1
21000001                                                NaN         6
21000002                                            ^5^,^3^         1
21000003  ^10_18^,^6_18^,^11_18^,^5_18^,^10_16^,^5_16^,^...         4
21000004                                                NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 21000000 to 21999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998679 non-null   object
 3   assigned_user_id  998679 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519190 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 21000000 to 21999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998679 non-null   object
 3   assigned_user_id  998679 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519190 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
22000000   1674222817.23672.18  89128558557   null_status                1
22000001    1674305942.97424.7  89270802932   null_status                1
22000002    1673845545.2630.35  89145446567   null_status                1
22000003  1674134695.117229.25  89046164003   null_status                1
22000004    1672992760.19128.4  89106526769   null_status                1

          last_step  ochered            call_date  \
22000000          2     9289  2023-01-20 13:53:38
22000001        111     9202  2023-01-21 12:59:03
22000002        105     9100  2023-01-16 05:05:45
22000003        261     9204  2023-01-19 13:24:56
22000004        250     9255  2023-01-06 08:12:41

                                          ptv_c  region_c
22000000                                 ^11_c^         7
22000001                                    NaN         5
22000002                      ^10^,^5^,^6^,^11^         1
22000003                                    NaN         7
22000004  ^3_o^,^6_o^,^11_o^,^5_o^,^6_c^,^11_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 22000000 to 22999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518752 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 22000000 to 22999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518752 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
23000000    1673934347.4176.6  89041445151   null_status                1
23000001  1673443772.38144.24  89203658756   null_status                1
23000002  1674473603.81698.35  89507393489   null_status                1
23000003   1674989256.41144.5  89525980655   null_status                1
23000004   1674639329.56467.6  89185023476   null_status                1

          last_step  ochered            call_date  \
23000000        261     9170  2023-01-17 05:45:48
23000001          2     9062  2023-01-11 13:29:33
23000002          2     9135  2023-01-23 11:33:25
23000003        102     9028  2023-01-29 10:47:37
23000004        250     9048  2023-01-25 09:35:30

                                       ptv_c  region_c
23000000                                 NaN         6
23000001      ^10_21^,^3_21^,^5_21^,^263_21^         4
23000002  ^11^,^5^,^3^,^3_20^,^5_20^,^11_20^         1
23000003                                 NaN         5
23000004                              ^5_16^         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 23000000 to 23999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998647 non-null   object
 3   assigned_user_id  998647 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519802 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 23000000 to 23999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998647 non-null   object
 3   assigned_user_id  998647 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519802 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None

                      uniqueid        phone client_status assigned_user_id  \
24000000   1674717055.24391.26  89154389040   null_status                1
24000001    1673609391.3575.16  89828284627   null_status                1
24000002    1674625435.6087.27  89145630958   null_status                1
24000003  1675004311.120589.29  89827814981   null_status                1
24000004  1674744128.130716.32  89308849726   null_status                1

          last_step  ochered            call_date                     ptv_c  \
24000000          3     9180  2023-01-26 07:10:56            ^10^,^11^,^19^
24000001        321     9212  2023-01-13 11:29:53  ^5^,^6^,^3^,^11_c^,^6_c^
24000002          8     9004  2023-01-25 05:43:56                       NaN
24000003        261     9215  2023-01-29 14:58:32                       NaN
24000004        106     9050  2023-01-26 14:42:09                       NaN

          region_c
24000000         1
24000001         1
24000002         2
24000003         5
24000004         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 24000000 to 24999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998695 non-null   object
 3   assigned_user_id  998695 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519409 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 24000000 to 24999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998695 non-null   object
 3   assigned_user_id  998695 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519409 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
25000000    1674983034.22050.4  89185636466   null_status                1
25000001  1673366822.168503.33  89153720268   null_status                1
25000002  1674824156.107644.30  89104203168   null_status                1
25000003   1674217084.98130.28  89102074984   null_status                1
25000004   1674030130.35235.25  89500018196   null_status                1

          last_step  ochered            call_date                   ptv_c  \
25000000        261     9077  2023-01-29 09:03:56            ^11_c^,^5_c^
25000001        102     9059  2023-01-10 16:07:03                  ^11_c^
25000002        261     9087  2023-01-27 12:55:57                  ^11_c^
25000003        250     9029  2023-01-20 12:18:05      ^10^,^5^,^19^,^11^
25000004         93     9020  2023-01-18 08:22:11  ^240_18^,^5_18^,^6_18^

          region_c
25000000         2
25000001         7
25000002         6
25000003         1
25000004         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 25000000 to 25999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998712 non-null   object
 3   assigned_user_id  998712 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518961 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 25000000 to 25999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998712 non-null   object
 3   assigned_user_id  998712 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518961 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
26000000    1674191669.3216.7  89614613347           NaN              NaN
26000001   1674471563.6232.15  89502108856   null_status                1
26000002  1674287899.19511.32  89879892366   null_status                1
26000003   1674369140.5090.34  89231763075   null_status                1
26000004  1673951728.24426.22  89777965260   null_status                1

          last_step  ochered            call_date  \
26000000        262     9200  2023-01-20 05:14:30
26000001        261     9200  2023-01-23 10:59:24
26000002        102     9028  2023-01-21 07:58:20
26000003        261     9170  2023-01-22 06:32:21
26000004          2     9090  2023-01-17 10:35:29

                                   ptv_c  region_c
26000000                             NaN         0
26000001                             ^5^         1
26000002  ^10^,^5^,^19^,^3^,^6_o^,^11_o^         1
26000003           ^5^,^11^,^11_c^,^5_c^         1
26000004                             NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 26000000 to 26999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998646 non-null   object
 3   assigned_user_id  998646 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518291 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 26000000 to 26999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998646 non-null   object
 3   assigned_user_id  998646 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518291 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status  \
27000000   1672909836.41817.34  89878637612      refusing
27000001  1673353991.105362.29  89139485068   null_status
27000002   1674549766.49406.35  89154665814   null_status
27000003   1674047785.12072.21  89287674473   null_status
27000004   1673284427.161175.7  89183563656   null_status

                              assigned_user_id  last_step  ochered  \
27000000  39a42527-478e-b33b-e56e-6210ea6ea6f1         97     9100
27000001                                     1          2     9185
27000002                                     1          2     9059
27000003                                     1        261     9025
27000004                                     1        106     9025

                    call_date                             ptv_c  region_c
27000000  2023-01-05 09:10:37  ^5^,^3^,^6^,^5_16^,^3_16^,^11_o^         1
27000001  2023-01-10 12:33:12                          ^5^,^11^         1
27000002  2023-01-24 08:42:47                               NaN         6
27000003  2023-01-18 13:16:26                               NaN         7
27000004  2023-01-09 17:13:48                               NaN         2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 27000000 to 27999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998638 non-null   object
 3   assigned_user_id  998638 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518839 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 27000000 to 27999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998638 non-null   object
 3   assigned_user_id  998638 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518839 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
28000000   1673343446.53706.34  89264755029   null_status                1
28000001   1674896972.38588.30  89629015779   null_status                1
28000002   1673432120.28965.22  89524639565   null_status                1
28000003   1672922947.430018.1  89086217099   null_status                1
28000004  1674729195.1427389.1  89519326077   null_status                1

          last_step  ochered            call_date  \
28000000          2     9059  2023-01-10 09:37:28
28000001        102     9028  2023-01-28 09:09:33
28000002        261     9013  2023-01-11 10:15:21
28000003         10     9017  2023-01-05 12:49:08
28000004        261     9215  2023-01-26 10:33:16

                                             ptv_c  region_c
28000000                                    ^11_c^         7
28000001  ^10^,^5^,^14^,^22^,^11^,^19^,^3_o^,^6_o^         1
28000002                                    ^11_c^         7
28000003                                     ^5_c^         1
28000004                                       NaN         5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 28000000 to 28999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998740 non-null   object
 3   assigned_user_id  998740 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518150 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 28000000 to 28999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998740 non-null   object
 3   assigned_user_id  998740 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518150 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
29000000  1673600738.13168.23  89268915818   null_status                1
29000001   1673607313.77608.6  89057171965   null_status                1
29000002  1675163588.81525.33  89687082969   null_status                1
29000003   1673604302.64526.7  89063820121   null_status                1
29000004   1674029814.6237.24  89200020506   null_status                1

          last_step  ochered            call_date  \
29000000        111     9059  2023-01-13 09:05:39
29000001        102     9270  2023-01-13 10:55:14
29000002        102     9270  2023-01-31 11:13:10
29000003        261     9131  2023-01-13 10:05:03
29000004         10     9140  2023-01-18 08:16:55

                                                      ptv_c  region_c
29000000                                                NaN         6
29000001  ^10_18^,^5_18^,^11_18^,^239_18^,^14_18^,^10_16...         2
29000002                                                NaN         5
29000003                                                NaN         5
29000004                      ^11_21^,^10_21^,^3_21^,^5_21^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 29000000 to 29999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998793 non-null   object
 3   assigned_user_id  998793 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518904 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 29000000 to 29999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998793 non-null   object
 3   assigned_user_id  998793 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518904 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
30000000     1672735397.607.35  89633182673   null_status                1
30000001    1673428345.5399.24  89241313222   null_status                1
30000002   1674130128.96786.29  89670085341   null_status                1
30000003   1675161235.15997.22  89067712727   null_status                1
30000004  1674577802.173150.32  89383479240   null_status                1

          last_step  ochered            call_date  \
30000000        261     9135  2023-01-03 08:43:17
30000001          2     9270  2023-01-11 09:12:26
30000002        261     9022  2023-01-19 12:08:49
30000003          2     9059  2023-01-31 10:33:55
30000004        261     9291  2023-01-24 16:30:03

                                                      ptv_c  region_c
30000000                                  ^5^,^19^,^3^,^11^         1
30000001                                                NaN         1
30000002  ^5_17^,^11_17^,^239_17^,^10_16^,^5_16^,^11_16^...         1
30000003                                                NaN         6
30000004                                                NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 30000000 to 30999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998716 non-null   object
 3   assigned_user_id  998716 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519300 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 30000000 to 30999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998716 non-null   object
 3   assigned_user_id  998716 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519300 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
31000000   1673083855.24630.7  89286309063   null_status                1
31000001  1674983828.35762.32  89257036763   null_status                1
31000002  1673597925.35037.33  89206170143   null_status                1
31000003   1674470524.7958.20  89145092564   null_status                1
31000004   1673251139.19227.5  89140713388   null_status                1

          last_step  ochered            call_date ptv_c  region_c
31000000         10     9025  2023-01-07 09:30:56   NaN         6
31000001        250     9059  2023-01-29 09:17:09   NaN         6
31000002          2     9207  2023-01-13 08:18:46   ^5^         1
31000003          2     9290  2023-01-23 10:42:05   NaN         4
31000004        209     9030  2023-01-09 07:59:01   NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 31000000 to 31999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998683 non-null   object
 3   assigned_user_id  998683 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519268 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 31000000 to 31999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998683 non-null   object
 3   assigned_user_id  998683 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519268 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
32000000  1674220509.16563.18  89610063761   null_status                1
32000001   1672903821.13058.5  89997854268   null_status                1
32000002  1674492827.111573.3  89197299957   null_status                1
32000003  1673940512.21054.35  89019566196   null_status                1
32000004  1673946222.48844.33  89212147786   null_status                1

          last_step  ochered            call_date ptv_c  region_c
32000000        261     9050  2023-01-20 13:15:11   NaN         7
32000001          2     9262  2023-01-05 07:30:22  ^10^         1
32000002        111     9090  2023-01-23 16:53:48   NaN         6
32000003        261     9290  2023-01-17 07:28:33   NaN         6
32000004        102     9213  2023-01-17 09:03:43   NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 32000000 to 32999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998674 non-null   object
 3   assigned_user_id  998674 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519142 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 32000000 to 32999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998674 non-null   object
 3   assigned_user_id  998674 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519142 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
33000000    1674561807.72647.4  89234141169   null_status                1
33000001  1674047033.112737.30  89282621111   null_status                1
33000002    1673352305.67496.4  89039700128   null_status                1
33000003   1674996547.92373.33  89299309586   null_status                1
33000004     1673494952.867.30  89082011599   null_status                1

          last_step  ochered            call_date           ptv_c  region_c
33000000        261     9072  2023-01-24 12:03:28          ^5_19^         7
33000001        261     9170  2023-01-18 13:03:54  ^5_16^,^11_16^         1
33000002        102     9270  2023-01-10 12:05:06             NaN         2
33000003        250     9059  2023-01-29 12:49:08             NaN         6
33000004        105     9290  2023-01-12 03:42:33     ^6_c^,^5_c^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 33000000 to 33999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998674 non-null   object
 3   assigned_user_id  998674 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518580 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 33000000 to 33999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998674 non-null   object
 3   assigned_user_id  998674 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518580 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status  \
34000000   1674285651.11547.29  89788846227   null_status
34000001    1673616558.83120.4  89061221644      refusing
34000002  1674734497.1440182.1  89826669125   null_status
34000003  1674220731.113387.33  89587155434   null_status
34000004    1674563057.76579.5  89629362075   null_status

                              assigned_user_id  last_step  ochered  \
34000000                                     1        102     9025
34000001  adefae5d-fbbf-f2b0-9c5f-63a5a6895caf         81     9267
34000002                                     1          2     9021
34000003                                     1        261     9090
34000004                                     1          2     9022

                    call_date                               ptv_c  region_c
34000000  2023-01-21 07:20:52                                 NaN         6
34000001  2023-01-13 13:29:19                            ^5^,^11^         1
34000002  2023-01-26 12:01:38               ^3_20^,^5_20^,^11_20^         4
34000003  2023-01-20 13:18:54                                 NaN         5
34000004  2023-01-24 12:24:19  ^10^,^11^,^10_17^,^11_17^,^239_17^         1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 34000000 to 34999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998782 non-null   object
 3   assigned_user_id  998782 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518779 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 34000000 to 34999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998782 non-null   object
 3   assigned_user_id  998782 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518779 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
35000000   1673335718.19180.34  89234143215   null_status                1
35000001  1674921384.130578.27  89190281021   null_status                1
35000002   1673524090.95810.35  89211103609   null_status                1
35000003   1673171078.29588.24  89690230619   null_status                1
35000004   1674548305.41605.25  89053245663   null_status                1

          last_step  ochered            call_date       ptv_c  region_c
35000000         10     9200  2023-01-10 07:28:39         NaN         7
35000001        261     9004  2023-01-28 15:56:25  ^5^,^5_18^         1
35000002        111     9213  2023-01-12 11:48:11         NaN         7
35000003        261     9090  2023-01-08 09:44:39         NaN         6
35000004         20     9077  2023-01-24 08:18:26      ^11_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 35000000 to 35999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998699 non-null   object
 3   assigned_user_id  998699 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519117 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 35000000 to 35999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998699 non-null   object
 3   assigned_user_id  998699 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519117 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
36000000   1673787693.376959.1  89022519251   null_status                1
36000001    1672916234.7229.18  89094114638   null_status                1
36000002    1674562203.73861.4  89506978789   null_status                1
36000003    1673172661.51685.3  89139274484   null_status                1
36000004  1674321304.141994.28  89307503733   null_status                1

          last_step  ochered            call_date        ptv_c  region_c
36000000          2     9204  2023-01-15 13:01:34  ^6_c^,^5_c^         2
36000001        106     9025  2023-01-05 10:57:15          NaN         6
36000002          2     9255  2023-01-24 12:10:04          NaN         7
36000003         10     9290  2023-01-08 10:11:02         ^25^         5
36000004        261     9255  2023-01-21 17:15:05          NaN         5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 36000000 to 36999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998748 non-null   object
 3   assigned_user_id  998748 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519216 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 36000000 to 36999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998748 non-null   object
 3   assigned_user_id  998748 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519216 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
37000000   1674034466.55380.32  89298611215   null_status                1
37000001   1672913143.58110.31  89965942744   null_status                1
37000002    1674979581.12288.5  89285933817   null_status                1
37000003  1672927929.127918.29  89116842162   null_status                1
37000004   1673685956.28155.27  89523598798   null_status                1

          last_step  ochered            call_date  \
37000000        261     9291  2023-01-18 09:34:27
37000001        261     9021  2023-01-05 10:05:44
37000002         10     9025  2023-01-29 08:06:22
37000003        106     9017  2023-01-05 14:12:10
37000004        261     9214  2023-01-14 08:45:57

                                  ptv_c  region_c
37000000                            NaN         6
37000001  ^10_19^,^6_19^,^5_19^,^11_19^         5
37000002                            NaN         2
37000003                          ^5_c^         1
37000004                            NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 37000000 to 37999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998747 non-null   object
 3   assigned_user_id  998747 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518433 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 37000000 to 37999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998747 non-null   object
 3   assigned_user_id  998747 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518433 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None

                     uniqueid        phone client_status assigned_user_id  \
38000000   1674997754.96648.6  89522685210   null_status                1
38000001  1673424833.34949.30  89681314001   null_status                1
38000002  1673607777.47407.22  89771674320   null_status                1
38000003  1673438614.99584.26  89297827949   null_status                1
38000004   1674454282.6638.34  89995715263   null_status                1

          last_step  ochered            call_date                 ptv_c  \
38000000        261     9204  2023-01-29 13:09:15                   NaN
38000001          2     9118  2023-01-11 08:13:54         ^5^,^11^,^19^
38000002          4     9051  2023-01-13 11:02:57                   ^5^
38000003        261     9291  2023-01-11 12:03:36                   NaN
38000004        111     9235  2023-01-23 06:11:23  ^5^,^11^,^19^,^11_c^

          region_c
38000000         6
38000001         1
38000002         1
38000003         6
38000004         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 38000000 to 38999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998733 non-null   object
 3   assigned_user_id  998733 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518853 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 38000000 to 38999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998733 non-null   object
 3   assigned_user_id  998733 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518853 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
39000000   1674728490.70105.27  89274395915   null_status                1
39000001    1674901806.58346.6  89375075678   null_status                1
39000002    1675173706.86409.5  89613153997   null_status                1
39000003  1674471399.1113294.1  89641613696   null_status                1
39000004  1673009498.105674.29  89772816762   null_status                1

          last_step  ochered            call_date  \
39000000        209     9218  2023-01-26 10:21:32
39000001        261     9291  2023-01-28 10:30:07
39000002        102     9077  2023-01-31 14:01:46
39000003          2     9255  2023-01-23 10:56:40
39000004          2     9059  2023-01-06 12:51:39

                                           ptv_c  region_c
39000000                                     NaN         6
39000001  ^3_o^,^6_o^,^11_o^,^5_o^,^19_o^,^10_o^         5
39000002                                     NaN         6
39000003                                     NaN         7
39000004                                     NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 39000000 to 39999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998724 non-null   object
 3   assigned_user_id  998724 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518927 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 39000000 to 39999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998724 non-null   object
 3   assigned_user_id  998724 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518927 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
40000000  1673103168.11038.17  89500231613   null_status                1
40000001   1674022817.7896.31  89534711718   null_status                1
40000002  1674907226.79133.25  89657233254   null_status                1
40000003  1674651666.19502.22  89507163750   null_status                1
40000004    1673935583.5885.7  89137093894   null_status                1

          last_step  ochered            call_date  \
40000000         10     9214  2023-01-07 14:52:49
40000001          2     9255  2023-01-18 06:20:18
40000002        261     9062  2023-01-28 12:00:27
40000003        106     9050  2023-01-25 13:01:07
40000004        261     9020  2023-01-17 06:06:24

                                                      ptv_c  region_c
40000000                                                NaN         5
40000001                                                NaN         5
40000002                                             ^5_17^         7
40000003                                                NaN         7
40000004  ^5^,^3^,^6_18^,^5_18^,^11_18^,^3_18^,^5_17^,^1...         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 40000000 to 40999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998686 non-null   object
 3   assigned_user_id  998686 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519437 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 40000000 to 40999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998686 non-null   object
 3   assigned_user_id  998686 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519437 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
41000000   1674811390.53602.33  89172988622   null_status                1
41000001   1673351107.52962.17  89377098218   null_status                1
41000002  1673269799.108976.29  89537161317   null_status                1
41000003   1674382333.39907.25  89674435555   null_status                1
41000004  1673791159.105074.26  89045069651   null_status                1

          last_step  ochered            call_date  \
41000000        101     9077  2023-01-27 09:23:11
41000001        261     9213  2023-01-10 11:45:08
41000002        261     9170  2023-01-09 13:10:00
41000003        209     9121  2023-01-22 10:12:15
41000004          2     9179  2023-01-15 13:59:20

                                         ptv_c  region_c
41000000                   ^11_c^,^5_c^,^11_c^         2
41000001                                   NaN         6
41000002                                 ^5_c^         1
41000003                    ^5^,^3^,^11^,^6_o^         1
41000004  ^6^,^11^,^6_19^,^5_19^,^6_20^,^5_20^         1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 41000000 to 41999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998777 non-null   object
 3   assigned_user_id  998777 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518879 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 41000000 to 41999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998777 non-null   object
 3   assigned_user_id  998777 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518879 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
42000000  1674484935.132326.25  89524667674   null_status                1
42000001  1674315884.132687.32  89514625101   null_status                1
42000002    1672918075.58327.5  89374467390   null_status                1
42000003   1673434703.81717.33  89539536738   null_status                1
42000004   1674562771.109513.6  89096559770   null_status                1

          last_step  ochered            call_date  \
42000000        102     9013  2023-01-23 14:42:16
42000001        261     9234  2023-01-21 15:44:45
42000002        111     9171  2023-01-05 11:27:56
42000003         10     9262  2023-01-11 10:58:24
42000004          2     9234  2023-01-24 12:19:32

                                 ptv_c  region_c
42000000                           ^5^         1
42000001                           NaN         7
42000002                          ^11^         1
42000003  ^10^,^5^,^11^,^5_17^,^10_17^         1
42000004                  ^5_c^,^11_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 42000000 to 42999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998643 non-null   object
 3   assigned_user_id  998643 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519684 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 42000000 to 42999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998643 non-null   object
 3   assigned_user_id  998643 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519684 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
43000000     1674568947.898.21  89001313720   null_status                1
43000001  1675001749.112952.27  89252961150   null_status                1
43000002     1675171832.265.18  89161129623   null_status                1
43000003    1673330464.5054.28  89617094917   null_status                1
43000004    1675078944.9961.16  89296288700   null_status                1

          last_step  ochered            call_date               ptv_c  \
43000000        261     9179  2023-01-24 14:02:28  ^5^,^6^,^11^,^3_o^
43000001        261     9028  2023-01-29 14:15:50                 NaN
43000002        102     9059  2023-01-31 13:30:33                 NaN
43000003        106     9031  2023-01-10 06:01:05                 NaN
43000004        209     9090  2023-01-30 11:42:26                 NaN

          region_c
43000000         1
43000001         5
43000002         6
43000003         6
43000004         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 43000000 to 43999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998713 non-null   object
 3   assigned_user_id  998713 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519048 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 43000000 to 43999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998713 non-null   object
 3   assigned_user_id  998713 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519048 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
44000000  1675003770.118203.25  89226086040   null_status                1
44000001   1672829766.66598.29  89221384165   null_status                1
44000002   1673346730.69199.26  89788870326   null_status                1
44000003   1673102583.32782.16  89990206722   null_status                1
44000004    1674286517.14399.7  89536002652   null_status                1

          last_step  ochered            call_date  \
44000000        261     9077  2023-01-29 14:49:31
44000001          2     9021  2023-01-04 10:56:07
44000002          2     9291  2023-01-10 10:32:11
44000003        261     9204  2023-01-07 14:43:04
44000004        250     9234  2023-01-21 07:35:18

                                                ptv_c  region_c
44000000                                 ^11_c^,^5_c^         1
44000001  ^10_18^,^6_18^,^5_18^,^3_17^,^11_17^,^5_17^         5
44000002                                       ^11_c^         7
44000003                                          NaN         7
44000004                                          NaN         4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 44000000 to 44999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998709 non-null   object
 3   assigned_user_id  998709 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519967 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 44000000 to 44999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998709 non-null   object
 3   assigned_user_id  998709 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519967 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
45000000  1673797022.125667.28  89823372764   null_status                1
45000001  1674052799.138411.28  89811097147   null_status                1
45000002  1675178023.141656.32  89048301373   null_status                1
45000003  1675181050.152768.30  89154526804   null_status                1
45000004   1673259997.66618.32  89179179631   null_status                1

          last_step  ochered            call_date              ptv_c  region_c
45000000          2     9100  2023-01-15 15:37:03   ^5^,^3^,^6^,^11^         1
45000001        261     9214  2023-01-18 14:40:01                NaN         6
45000002        101     9077  2023-01-31 15:13:44             ^11_c^         2
45000003        102     9059  2023-01-31 16:04:11                NaN         6
45000004         10     9267  2023-01-09 10:26:38  ^3^,^11^,^g3_100^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 45000000 to 45999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998701 non-null   object
 3   assigned_user_id  998701 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518847 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 45000000 to 45999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998701 non-null   object
 3   assigned_user_id  998701 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518847 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
46000000   1673095118.8119.22  89389904041   null_status                1
46000001  1673092329.18437.15  89653906496   null_status                1
46000002   1673337691.27546.6  89258161492   null_status                1
46000003   1673174778.84660.6  89875588163   null_status                1
46000004    1672814660.6109.7  89271772309   null_status                1

          last_step  ochered            call_date  \
46000000        111     9013  2023-01-07 12:38:39
46000001        102     9059  2023-01-07 11:52:10
46000002        250     9017  2023-01-10 08:01:32
46000003          1     9140  2023-01-08 10:46:19
46000004         10     9289  2023-01-04 06:44:21

                                                      ptv_c  region_c
46000000                                                NaN         6
46000001                                                NaN         6
46000002  ^10_16^,^5_16^,^11_16^,^239_16^,^19_16^,^5_12^...         2
46000003                                     ^5_18^,^11_18^         2
46000004                                                NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 46000000 to 46999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998665 non-null   object
 3   assigned_user_id  998665 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518831 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 46000000 to 46999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998665 non-null   object
 3   assigned_user_id  998665 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518831 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
47000000    1674286690.15172.6  89243681479   null_status                1
47000001    1673349806.58359.5  89919228770   null_status                1
47000002   1673343124.52818.25  89206043492   null_status                1
47000003  1674488425.147220.33  89512676765   null_status                1
47000004   1674197631.822418.1  89510656988   null_status                1

          last_step  ochered            call_date              ptv_c  region_c
47000000        111     9060  2023-01-21 07:38:11                NaN         7
47000001        261     9090  2023-01-10 11:23:27             ^11_c^         7
47000002        261     9255  2023-01-10 09:32:08                NaN         6
47000003        261     9234  2023-01-23 15:40:26                NaN         7
47000004        111     9267  2023-01-20 06:53:52  ^10^,^5^,^3^,^11^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 47000000 to 47999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998742 non-null   object
 3   assigned_user_id  998742 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518741 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 47000000 to 47999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998742 non-null   object
 3   assigned_user_id  998742 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518741 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
48000000   1673950072.22988.20  89260129274   null_status                1
48000001    1673097192.87213.6  89183272960   null_status                1
48000002  1673614278.109428.31  89265803381   null_status                1
48000003    1672818153.15584.7  89997933566   null_status                1
48000004    1674031961.3137.24  89227655259   null_status                1

          last_step  ochered            call_date  \
48000000        250     9118  2023-01-17 10:07:53
48000001         10     9291  2023-01-07 13:13:13
48000002        261     9118  2023-01-13 12:51:19
48000003        250     9060  2023-01-04 07:42:34
48000004          1     9215  2023-01-18 08:52:42

                                                      ptv_c  region_c
48000000  ^10^,^5^,^14^,^22^,^11^,^19^,^5_17^,^19_17^,^1...         1
48000001                                                NaN         5
48000002           ^10^,^5^,^14^,^22^,^11^,^19^,^3_o^,^6_o^         1
48000003                                                NaN         7
48000004                                           ^5^,^11^         1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 48000000 to 48999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998680 non-null   object
 3   assigned_user_id  998680 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519454 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 48000000 to 48999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998680 non-null   object
 3   assigned_user_id  998680 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519454 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
49000000  1672844671.128031.29  89057357493   null_status                1
49000001    1672842637.84110.5  89602179140   null_status                1
49000002     1673682150.9648.3  89996131725   null_status                1
49000003    1675148971.12535.4  89532815365   null_status                1
49000004  1675169872.108378.31  89196430563   null_status                1

          last_step  ochered            call_date  \
49000000          2     9022  2023-01-04 15:04:32
49000001        261     9204  2023-01-04 14:30:38
49000002          2     9022  2023-01-14 07:42:31
49000003        102     9004  2023-01-31 07:09:32
49000004          2     9087  2023-01-31 12:57:53

                                                      ptv_c  region_c
49000000  ^10^,^5^,^14^,^22^,^11^,^10_18^,^5_18^,^11_18^...         1
49000001                                                NaN         7
49000002                            ^10^,^5^,^22^,^11^,^19^         1
49000003                                       ^10^,^5^,^3^         1
49000004                                                NaN         5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 49000000 to 49999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998633 non-null   object
 3   assigned_user_id  998633 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519011 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 49000000 to 49999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998633 non-null   object
 3   assigned_user_id  998633 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519011 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
50000000   1674548777.44377.25  89039002180   null_status                1
50000001    1674887038.6398.32  89088605843   null_status                1
50000002  1673714831.140747.29  89650121609   null_status                1
50000003    1674809988.46721.6  89061530006   null_status                1
50000004    1674901221.7612.24  89886388970   null_status                1

          last_step  ochered            call_date                   ptv_c  \
50000000         10     9200  2023-01-24 08:26:19                     NaN
50000001        261     9235  2023-01-28 06:23:59       ^5_19^,^5_17^,^5^
50000002         10     9204  2023-01-14 16:47:12                   ^5_c^
50000003        102     9140  2023-01-27 08:59:49  ^10_18^,^5_18^,^11_18^
50000004          8     9009  2023-01-28 10:20:22                     NaN

          region_c
50000000         5
50000001         1
50000002         2
50000003         4
50000004         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 50000000 to 50999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998717 non-null   object
 3   assigned_user_id  998717 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519112 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 50000000 to 50999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998717 non-null   object
 3   assigned_user_id  998717 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519112 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status  \
51000000   1672821330.28290.32  89209696517   null_status
51000001  1673883822.149914.35  89658825201   null_status
51000002   1673167305.687669.1  89121577556      refusing
51000003   1674467747.56123.26  89874777066   null_status
51000004   1674558714.91149.29  89530549220   null_status

                              assigned_user_id  last_step  ochered  \
51000000                                     1        409     9255
51000001                                     1        261     9087
51000002  34131642-3172-001f-a2a9-635638392ce7         81     9196
51000003                                     1          2     9029
51000004                                     1        102     9212

                    call_date            ptv_c  region_c
51000000  2023-01-04 08:35:31              NaN         7
51000001  2023-01-16 15:43:43           ^11_c^         7
51000002  2023-01-08 08:41:46     ^11_c^,^5_c^         1
51000003  2023-01-23 09:55:48  ^5^,^11^,^5_18^         7
51000004  2023-01-24 11:11:55            ^5_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 51000000 to 51999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998698 non-null   object
 3   assigned_user_id  998698 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519509 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 51000000 to 51999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998698 non-null   object
 3   assigned_user_id  998698 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519509 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
52000000  1673441419.115048.30  89613229376   null_status                1
52000001  1674486842.140322.32  89122672694   null_status                1
52000002   1674033911.53160.30  89261384457   null_status                1
52000003    1673857318.36167.6  89277557085   null_status                1
52000004   1674125660.75924.33  89186535449   null_status                1

          last_step  ochered            call_date  \
52000000        261     9179  2023-01-11 12:50:22
52000001        102     9215  2023-01-23 15:14:03
52000002          2     9090  2023-01-18 09:25:13
52000003         10     9204  2023-01-16 08:21:59
52000004        102     9291  2023-01-19 10:54:21

                                                      ptv_c  region_c
52000000  ^10_15^,^6_15^,^5_15^,^11_15^,^3_15^,^10_17^,^...         4
52000001                                                NaN         6
52000002                                             ^11_c^         7
52000003                                                ^5^         1
52000004                                                NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 52000000 to 52999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998645 non-null   object
 3   assigned_user_id  998645 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519133 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 52000000 to 52999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998645 non-null   object
 3   assigned_user_id  998645 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519133 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
53000000   1674816947.77039.25  89500808044   null_status                1
53000001    1674988099.53645.6  89205839282   null_status                1
53000002    1673611604.67850.4  89175183037   null_status                1
53000003     1673591893.7339.4  89113167361   null_status                1
53000004  1674658582.140694.32  89014415497   null_status                1

          last_step  ochered            call_date  \
53000000        322     9200  2023-01-27 10:55:48
53000001        102     9028  2023-01-29 10:28:20
53000002        261     9271  2023-01-13 12:06:45
53000003        322     9203  2023-01-13 06:38:14
53000004        102     9202  2023-01-25 14:56:23

                                                      ptv_c  region_c
53000000                                                NaN         5
53000001                                                NaN         5
53000002  ^5_16^,^11_16^,^19_16^,^239_16^,^5_12^,^263_12...         4
53000003                                                ^5^         1
53000004                                       ^5_c^,^11_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 53000000 to 53999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998655 non-null   object
 3   assigned_user_id  998655 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519363 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 53000000 to 53999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998655 non-null   object
 3   assigned_user_id  998655 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519363 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
54000000  1674922176.131872.30  89034003368   null_status                1
54000001   1673349277.46249.21  89297730020   null_status                1
54000002   1674913591.104442.6  89280709789   null_status                1
54000003    1674470963.69691.6  89165908733   null_status                1
54000004  1674743288.126991.26  89280768125   null_status                1

          last_step  ochered            call_date          ptv_c  region_c
54000000        261     9291  2023-01-28 16:09:37            NaN         6
54000001          2     9140  2023-01-10 11:14:38  ^10^,^5^,^11^         1
54000002          8     9004  2023-01-28 13:46:32     ^5^,^5_18^         1
54000003         10     9059  2023-01-23 10:49:25            NaN         6
54000004        102     9291  2023-01-26 14:28:09            NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 54000000 to 54999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998731 non-null   object
 3   assigned_user_id  998731 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519915 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 54000000 to 54999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998731 non-null   object
 3   assigned_user_id  998731 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519915 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None

                      uniqueid        phone client_status assigned_user_id  \
55000000  1674922225.132550.26  89894597118   null_status                1
55000001     1674965358.255.31  89632668037   null_status                1
55000002   1673351649.94071.30  89213449501   null_status                1
55000003  1673452232.169934.25  89775641186   null_status                1
55000004   1672817235.12545.25  89150741799   null_status                1

          last_step  ochered            call_date  \
55000000        111     9218  2023-01-28 16:10:26
55000001          2     9201  2023-01-29 04:09:19
55000002        261     9027  2023-01-10 11:54:11
55000003          2     9262  2023-01-11 15:50:33
55000004          2     9180  2023-01-04 07:27:16

                                              ptv_c  region_c
55000000                                        NaN         6
55000001                                        ^5^         1
55000002                                        ^5^         1
55000003         ^10^,^10_20^,^5_20^,^10_16^,^5_16^         1
55000004  ^5^,^11^,^3_o^,^11_o^,^5_o^,^19_o^,^10_o^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 55000000 to 55999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998624 non-null   object
 3   assigned_user_id  998624 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519542 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 55000000 to 55999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998624 non-null   object
 3   assigned_user_id  998624 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519542 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status  \
56000000    1674636391.29859.3  89678053990      refusing
56000001   1672917059.81050.25  89129001725   null_status
56000002   1674050806.129918.6  89272342235   null_status
56000003  1672926505.120411.33  89280753715   null_status
56000004    1673344901.42392.5  89961185206   null_status

                              assigned_user_id  last_step  ochered  \
56000000  2a6baf71-22c7-0ebd-bb6d-60c0e0f5580d         81     9140
56000001                                     1        322     9235
56000002                                     1         10     9202
56000003                                     1        101     9291
56000004                                     1          2     9289

                    call_date              ptv_c  region_c
56000000  2023-01-25 08:46:32  ^10^,^11^,^5^,^3^         1
56000001  2023-01-05 11:11:00                ^5^         1
56000002  2023-01-18 14:06:47       ^11_c^,^5_c^         2
56000003  2023-01-05 13:48:26                NaN         7
56000004  2023-01-10 10:01:43                NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 56000000 to 56999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998705 non-null   object
 3   assigned_user_id  998705 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             517944 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 56000000 to 56999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998705 non-null   object
 3   assigned_user_id  998705 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             517944 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
57000000    1674466693.35824.3  89243818585   null_status                1
57000001  1673965326.137530.28  89046974358   null_status                1
57000002  1674739042.110458.29  89043769128   null_status                1
57000003    1673089322.30633.5  89210775719   null_status                1
57000004  1673440597.110501.31  89023870383   null_status                1

          last_step  ochered            call_date              ptv_c  region_c
57000000        322     9204  2023-01-23 09:38:15                NaN         5
57000001        101     9262  2023-01-17 14:22:08  ^10^,^5^,^3^,^19^         1
57000002        102     9077  2023-01-26 13:17:24                NaN         2
57000003        111     9214  2023-01-07 11:02:03                NaN         7
57000004        111     9291  2023-01-11 12:36:39                NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 57000000 to 57999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998664 non-null   object
 3   assigned_user_id  998664 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519842 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 57000000 to 57999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998664 non-null   object
 3   assigned_user_id  998664 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519842 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
58000000    1673878902.90896.5  89023879572   null_status                1
58000001  1673976986.182948.35  89612754111   null_status                1
58000002   1673621826.214471.1  89118545498   null_status                1
58000003  1674654358.122221.36  89102106015   null_status                1
58000004    1673081692.18609.7  89015190869   null_status                1

          last_step  ochered            call_date  \
58000000        102     9204  2023-01-16 14:21:43
58000001         10     9179  2023-01-17 17:36:27
58000002         10     9204  2023-01-13 14:57:07
58000003        111     9184  2023-01-25 13:46:00
58000004          2     9090  2023-01-07 08:54:53

                                                      ptv_c  region_c
58000000                                                NaN         2
58000001               ^10_17^,^5_17^,^6_17^,^3_17^,^11_17^         5
58000002                                                NaN         4
58000003  ^3_20^,^11_20^,^10_18^,^19_18^,^3_18^,^11_18^,...         4
58000004                                                NaN         6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 58000000 to 58999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998663 non-null   object
 3   assigned_user_id  998663 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518991 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 58000000 to 58999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998663 non-null   object
 3   assigned_user_id  998663 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518991 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
59000000   1674027305.22321.27  89107540959   null_status                1
59000001  1674148670.150718.28  89257371353   null_status                1
59000002    1673017718.98156.3  89045551281   null_status                1
59000003    1674470187.67115.7  89221493331   null_status                1
59000004   1674569223.59906.19  89052073181   null_status                1

          last_step  ochered            call_date                    ptv_c  \
59000000         21     9029  2023-01-18 07:35:05  ^5^,^11^,^5_18^,^11_18^
59000001        261     9090  2023-01-19 17:17:51                      NaN
59000002        261     9214  2023-01-06 15:08:39                      NaN
59000003          2     9234  2023-01-23 10:36:28                      NaN
59000004        250     9204  2023-01-24 14:07:05                      NaN

          region_c
59000000         1
59000001         5
59000002         7
59000003         5
59000004         4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 59000000 to 59999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998751 non-null   object
 3   assigned_user_id  998751 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519139 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 59000000 to 59999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998751 non-null   object
 3   assigned_user_id  998751 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519139 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
60000000   1673515685.57522.6  89030722117   null_status                1
60000001    1673333403.7351.3  89313332878   null_status                1
60000002  1675074552.68930.31  89185434443   null_status                1
60000003   1673439723.73967.5  89161597856   null_status                1
60000004  1673090851.594634.1  89514280369   null_status                1

          last_step  ochered            call_date  \
60000000          2     9138  2023-01-12 09:28:06
60000001        261     9025  2023-01-10 06:50:03
60000002         10     9179  2023-01-30 10:29:13
60000003          2     9038  2023-01-11 12:22:05
60000004        261     9290  2023-01-07 11:27:32

                                                 ptv_c  region_c
60000000  ^5^,^11^,^3^,^3_o^,^6_o^,^11_o^,^5_o^,^11_c^         1
60000001                                           NaN         6
60000002          ^10^,^11^,^3^,^6^,^6_o^,^5_o^,^19_o^         1
60000003                                           ^5^         1
60000004                                           NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 60000000 to 60999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998730 non-null   object
 3   assigned_user_id  998730 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519023 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 60000000 to 60999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998730 non-null   object
 3   assigned_user_id  998730 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519023 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
61000000    1673332489.8740.6  89146476326   null_status                1
61000001  1673285236.114486.5  89615855445   null_status                1
61000002  1672825121.45176.25  89106375070   null_status                1
61000003  1672817663.13912.25  89160928899   null_status                1
61000004  1673685396.25465.31  89809037965   null_status                1

          last_step  ochered            call_date  \
61000000        261     9030  2023-01-10 06:34:49
61000001         10     9291  2023-01-09 17:27:17
61000002        250     9029  2023-01-04 09:38:42
61000003        318     9180  2023-01-04 07:34:24
61000004        111     9090  2023-01-14 08:36:37

                                                      ptv_c  region_c
61000000                                                NaN         6
61000001                                             ^11_c^         7
61000002                                   ^5^,^6^,^3^,^11^         1
61000003  ^10^,^5^,^14^,^22^,^11^,^10_19^,^5_19^,^11_19^...         1
61000004                                                NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 61000000 to 61999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998644 non-null   object
 3   assigned_user_id  998644 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518505 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 61000000 to 61999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998644 non-null   object
 3   assigned_user_id  998644 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518505 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
62000000    1672917656.57051.5  89034754713   null_status                1
62000001   1673688225.38188.29  89372286306   null_status                1
62000002   1674202507.32092.31  89261583994   null_status                1
62000003    1674662470.3765.18  89042954201   null_status                1
62000004  1674495806.166697.35  89194214455   null_status                1

          last_step  ochered            call_date  \
62000000         10     9087  2023-01-05 11:20:57
62000001        261     9087  2023-01-14 09:23:46
62000002          2     9028  2023-01-20 08:15:08
62000003          1     9050  2023-01-25 16:01:12
62000004         10     9025  2023-01-23 17:43:27

                                                      ptv_c  region_c
62000000  ^5^,^10_21^,^5_21^,^3_o^,^11_o^,^5_o^,^19_o^,^...         1
62000001                                   ^5^,^11_c^,^5_c^         1
62000002             ^19_16^,^5_16^,^5_12^,^263_12^,^19_12^         1
62000003                                                NaN         7
62000004                                                NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 62000000 to 62999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998711 non-null   object
 3   assigned_user_id  998711 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519225 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 62000000 to 62999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998711 non-null   object
 3   assigned_user_id  998711 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519225 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
63000000   1675150561.17318.4  89532141212   null_status                1
63000001   1674219829.8071.20  89126918944   null_status                1
63000002  1673423491.28829.25  89177800015   null_status                1
63000003  1673188104.141631.7  89238254727   null_status                1
63000004   1672831711.52145.5  89021781596   null_status                1

          last_step  ochered            call_date          ptv_c  region_c
63000000          3     9247  2023-01-31 07:36:02            NaN         2
63000001        261     9234  2023-01-20 13:03:50            NaN         6
63000002        261     9030  2023-01-11 07:51:32            NaN         2
63000003        261     9290  2023-01-08 14:28:24            NaN         6
63000004          1     9072  2023-01-04 11:28:32  ^5_16^,^5_17^         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 63000000 to 63999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998658 non-null   object
 3   assigned_user_id  998658 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519653 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 63000000 to 63999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998658 non-null   object
 3   assigned_user_id  998658 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519653 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
64000000  1674052504.137471.33  89655968550   null_status                1
64000001   1674643736.75473.28  89088347925   null_status                1
64000002   1673528781.28960.24  89058670821   null_status                1
64000003     1674530782.435.27  89994952448   null_status                1
64000004  1672839748.110378.29  89200704411   null_status                1

          last_step  ochered            call_date  \
64000000          2     9218  2023-01-18 14:35:06
64000001         10     9234  2023-01-25 10:48:58
64000002          2     9157  2023-01-12 13:06:22
64000003        261     9072  2023-01-24 03:26:23
64000004        111     9013  2023-01-04 13:42:29

                                   ptv_c  region_c
64000000                             NaN         6
64000001  ^3_o^,^6_o^,^11_o^,^5_o^,^5_c^         2
64000002     ^5^,^11^,^3^,^5_19^,^11_19^         1
64000003            ^5_20^,^3_17^,^5_17^         4
64000004                             NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 64000000 to 64999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998598 non-null   object
 3   assigned_user_id  998598 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519637 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 64000000 to 64999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998598 non-null   object
 3   assigned_user_id  998598 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519637 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
65000000  1673508163.21352.26  89179251614   null_status                1
65000001  1673854471.24323.27  89014549038   null_status                1
65000002     1674919590.85.21  89384306074   null_status                1
65000003  1673184106.20576.32  89298325726   null_status                1
65000004    1673935777.4189.5  89179069878   null_status                1

          last_step  ochered            call_date                  ptv_c  \
65000000        261     9267  2023-01-12 07:22:44  ^5_18^,^3_18^,^11_18^
65000001        261     9100  2023-01-16 07:34:33  ^10^,^6^,^11^,^5^,^3^
65000002        111     9291  2023-01-28 15:26:31                 ^11_c^
65000003        209     9291  2023-01-08 13:21:47                    NaN
65000004        250     9267  2023-01-17 06:09:38       ^11_19^,^g3_100^

          region_c
65000000         6
65000001         1
65000002         4
65000003         6
65000004         5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 65000000 to 65999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998626 non-null   object
 3   assigned_user_id  998626 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519523 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 65000000 to 65999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998626 non-null   object
 3   assigned_user_id  998626 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519523 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
66000000  1674742369.123540.33  89020803317   null_status                1
66000001   1673966973.101998.4  89313206752   null_status                1
66000002  1673623661.150456.29  89510513384   null_status                1
66000003    1673183939.86439.4  89881156888   null_status                1
66000004    1675158712.42305.3  89126853151   null_status                1

          last_step  ochered            call_date   ptv_c  region_c
66000000        250     9087  2023-01-26 14:12:50  ^11_c^         5
66000001        261     9214  2023-01-17 14:49:34     NaN         6
66000002          2     9289  2023-01-13 15:27:42     NaN         7
66000003          1     9291  2023-01-08 13:18:59     NaN         6
66000004          8     9004  2023-01-31 09:51:53     NaN         4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 66000000 to 66999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998721 non-null   object
 3   assigned_user_id  998721 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519261 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 66000000 to 66999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998721 non-null   object
 3   assigned_user_id  998721 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519261 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
67000000   1674124975.72836.31  89268351150   null_status                1
67000001   1674030011.34978.33  89171174582   null_status                1
67000002  1675176439.135682.36  89048379501   null_status                1
67000003  1673447133.145273.28  89613351671   null_status                1
67000004   1673426364.41901.35  89181785585   null_status                1

          last_step  ochered            call_date  \
67000000        261     9118  2023-01-19 10:42:56
67000001        111     9289  2023-01-18 08:20:12
67000002        261     9289  2023-01-31 14:47:20
67000003         10     9135  2023-01-11 14:25:35
67000004          2     9169  2023-01-11 08:39:25

                                                      ptv_c  region_c
67000000  ^10^,^14^,^5^,^22^,^11^,^19^,^5_18^,^10_17^,^5...         1
67000001                                                NaN         6
67000002                                             ^11_c^         4
67000003                                           ^5^,^11^         1
67000004                                      ^10^,^11^,^5^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 67000000 to 67999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998681 non-null   object
 3   assigned_user_id  998681 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518201 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 67000000 to 67999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998681 non-null   object
 3   assigned_user_id  998681 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518201 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                     uniqueid        phone client_status assigned_user_id  \
68000000  1674032758.47509.33  89644172283   null_status                1
68000001  1673688380.38659.34  89213035423   null_status                1
68000002  1672916997.76248.30  89043940966   null_status                1
68000003   1673177774.68856.4  89871317515   null_status                1
68000004   1673588096.3405.33  89502626725   null_status                1

          last_step  ochered            call_date    ptv_c  region_c
68000000        261     9060  2023-01-18 09:05:59      NaN         6
68000001          2     9214  2023-01-14 09:26:22      NaN         7
68000002          1     9013  2023-01-05 11:09:58      NaN         7
68000003          2     9202  2023-01-08 11:36:15      NaN         7
68000004          1     9100  2023-01-13 05:34:57  ^5^,^6^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 68000000 to 68999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998707 non-null   object
 3   assigned_user_id  998707 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519016 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 68000000 to 68999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998707 non-null   object
 3   assigned_user_id  998707 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519016 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None

                      uniqueid        phone client_status assigned_user_id  \
69000000    1672906873.21577.3  89145680859   null_status                1
69000001  1672922952.107411.26  89109973873   null_status                1
69000002    1675153422.5703.19  89308402584   null_status                1
69000003  1674922570.1658469.1  89172740357   null_status                1
69000004    1674466895.52855.7  89165353818   null_status                1

          last_step  ochered            call_date  \
69000000        261     9060  2023-01-05 08:21:14
69000001        261     9207  2023-01-05 12:49:13
69000002        261     9170  2023-01-31 08:23:43
69000003        261     9218  2023-01-28 16:16:12
69000004          2     9059  2023-01-23 09:41:36

                                  ptv_c  region_c
69000000                            NaN         7
69000001                            ^5^         1
69000002  ^10_17^,^5_17^,^6_17^,^11_17^         7
69000003                            NaN         6
69000004                            NaN         6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 69000000 to 69999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998622 non-null   object
 3   assigned_user_id  998622 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             520034 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 69000000 to 69999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998622 non-null   object
 3   assigned_user_id  998622 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             520034 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
70000000    1674650766.96912.7  89879496113   null_status                1
70000001    1674470553.8055.20  89506704513   null_status                1
70000002  1674051392.131351.26  89677619142   null_status                1
70000003   1673006070.88424.34  89267872958   null_status                1
70000004   1673626554.112269.5  89116187052   null_status                1

          last_step  ochered            call_date  \
70000000        102     9087  2023-01-25 12:46:07
70000001        111     9020  2023-01-23 10:42:34
70000002          2     9028  2023-01-18 14:16:33
70000003        111     9017  2023-01-06 11:54:31
70000004          2     9204  2023-01-13 16:15:55

                                  ptv_c  region_c
70000000                          ^5_c^         2
70000001                  ^6_17^,^5_17^         2
70000002  ^10_16^,^5_16^,^19_16^,^3_16^         2
70000003                          ^5_c^         2
70000004                            NaN         4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 70000000 to 70999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998668 non-null   object
 3   assigned_user_id  998668 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518994 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 70000000 to 70999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998668 non-null   object
 3   assigned_user_id  998668 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518994 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
71000000   1673451353.166448.7  89301047902   null_status                1
71000001  1674145952.163244.29  89093847572   null_status                1
71000002   1673347136.71225.28  89648884886   null_status                1
71000003   1675081067.10951.18  89270456942   null_status                1
71000004    1673619007.90611.4  89066054494   null_status                1

          last_step  ochered            call_date           ptv_c  region_c
71000000        261     9062  2023-01-11 15:35:54  ^5_16^,^10_16^         4
71000001        261     9291  2023-01-19 16:32:33             NaN         6
71000002        261     9077  2023-01-10 10:38:57          ^11_c^         6
71000003        261     9028  2023-01-30 12:17:48             NaN         7
71000004        102     9077  2023-01-13 14:10:09   ^19_c^,^11_c^         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 71000000 to 71999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519412 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 71000000 to 71999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519412 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
72000000   1674904367.68530.25  89377392678   null_status                1
72000001  1674742668.125066.27  89370037515   null_status                1
72000002    1675154635.9904.19  89680458115   null_status                1
72000003   1673259202.62854.25  89685220221   null_status                1
72000004    1675077881.84352.7  89283594483   null_status                1

          last_step  ochered            call_date         ptv_c  region_c
72000000         14     9077  2023-01-28 11:12:49           NaN         2
72000001          2     9218  2023-01-26 14:17:49        ^11_c^         7
72000002          2     9090  2023-01-31 08:43:57  ^5_17^,^_17^         4
72000003          2     9270  2023-01-09 10:13:23           NaN         2
72000004         10     9291  2023-01-30 11:24:42           NaN         6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 72000000 to 72999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998707 non-null   object
 3   assigned_user_id  998707 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519145 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 72000000 to 72999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998707 non-null   object
 3   assigned_user_id  998707 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519145 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
73000000     1674627860.1220.7  89030214343   null_status                1
73000001    1673255090.31573.4  89287642218   null_status                1
73000002  1674486046.135862.30  89118121264   null_status                1
73000003    1673782236.68879.6  89244643551   null_status                1
73000004  1672843111.124168.30  89991676073   null_status                1

          last_step  ochered            call_date    ptv_c  region_c
73000000          2     9030  2023-01-25 06:24:21    ^5_c^         2
73000001          2     9291  2023-01-09 09:04:50   ^11_c^         7
73000002        322     9204  2023-01-23 15:00:47      NaN         2
73000003        261     9100  2023-01-15 11:30:37  ^5^,^6^         1
73000004          2     9214  2023-01-04 14:38:32      NaN         7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 73000000 to 73999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             518553 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 73000000 to 73999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998722 non-null   object
 3   assigned_user_id  998722 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             518553 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
74000000   1674718248.29652.25  89147988270   null_status                1
74000001  1674044572.101840.35  89518790020   null_status                1
74000002     1673858471.502.24  89039352797   null_status                1
74000003  1674047919.116689.32  89006576115   null_status                1
74000004  1673876952.122768.29  89222230004   null_status                1

          last_step  ochered            call_date           ptv_c  region_c
74000000          4     9004  2023-01-26 07:30:49             NaN         2
74000001        250     9087  2023-01-18 12:22:53             NaN         1
74000002          2     9185  2023-01-16 08:41:12  ^5_18^,^11_18^         5
74000003        261     9204  2023-01-18 13:18:41             NaN         6
74000004        261     9234  2023-01-16 13:49:13             NaN         5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 74000000 to 74999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998747 non-null   object
 3   assigned_user_id  998747 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519559 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 74000000 to 74999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998747 non-null   object
 3   assigned_user_id  998747 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519559 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
75000000   1674466234.49494.36  89641182502   null_status                1
75000001  1674132269.106737.29  89001652006   null_status                1
75000002  1673966191.142634.27  89994574850   null_status                1
75000003    1673522672.89834.7  89095535464   null_status                1
75000004   1673004426.81433.35  89125958599   null_status                1

          last_step  ochered            call_date  \
75000000          2     9290  2023-01-23 09:30:35
75000001        261     9289  2023-01-19 12:44:30
75000002          2     9290  2023-01-17 14:36:32
75000003        105     9245  2023-01-12 11:24:33
75000004         10     9225  2023-01-06 11:27:07

                                                    ptv_c  region_c
75000000                                              NaN         7
75000001                                              NaN         7
75000002                                              NaN         6
75000003  ^240_20^,^10_20^,^5_20^,^5_16^,^240_16^,^10_16^         2
75000004                        ^5^,^3^,^11^,^6_o^,^10_o^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 75000000 to 75999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998684 non-null   object
 3   assigned_user_id  998684 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519067 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 75000000 to 75999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998684 non-null   object
 3   assigned_user_id  998684 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519067 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None

                      uniqueid        phone client_status assigned_user_id  \
76000000   1674891597.17659.25  89111923690   null_status                1
76000001   1674462718.33739.27  89393339621   null_status                1
76000002   1673269073.29463.17  89858990528   null_status                1
76000003  1674568772.134613.34  89925047777   null_status                1
76000004  1672843943.126683.26  89006541409   null_status                1

          last_step  ochered            call_date           ptv_c  region_c
76000000        261     9131  2023-01-28 07:39:58        ^5^,^19^         1
76000001          2     9267  2023-01-23 08:31:59  ^5_17^,^11_17^         6
76000002          2     9059  2023-01-09 12:57:54             NaN         6
76000003        111     9234  2023-01-24 13:59:33          ^11_c^         2
76000004        261     9214  2023-01-04 14:52:24             NaN         2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 76000000 to 76999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  int64
 2   client_status     998697 non-null   object
 3   assigned_user_id  998697 non-null   object
 4   last_step         1000000 non-null  int64
 5   ochered           1000000 non-null  int64
 6   call_date         1000000 non-null  object
 7   ptv_c             519758 non-null   object
 8   region_c          1000000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 68.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 76000000 to 76999999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   uniqueid          1000000 non-null  object
 1   phone             1000000 non-null  object
 2   client_status     998697 non-null   object
 3   assigned_user_id  998697 non-null   object
 4   last_step         1000000 non-null  object
 5   ochered           1000000 non-null  object
 6   call_date         1000000 non-null  object
 7   ptv_c             519758 non-null   object
 8   region_c          1000000 non-null  object
dtypes: object(9)
memory usage: 68.7+ MB
None
                      uniqueid        phone client_status assigned_user_id  \
77000000    1674889845.12106.7  89252808966   null_status                1
77000001  1673969822.157717.31  89151547321   null_status                1
77000002  1673617698.124588.25  89824531944   null_status                1
77000003  1673706536.118595.29  89772895556   null_status                1
77000004    1673509025.46199.1  89697242777   null_status                1

          last_step  ochered            call_date  \
77000000        261     9076  2023-01-28 07:10:45
77000001         15     9180  2023-01-17 15:37:03
77000002        111     9212  2023-01-13 13:48:20
77000003        261     9090  2023-01-14 14:28:57
77000004         20     9170  2023-01-12 07:37:06

                                                      ptv_c  region_c
77000000                           ^5_18^,^3_o^,^6_o^,^5_o^         2
77000001  ^10^,^5^,^14^,^22^,^11^,^19^,^10_21^,^10_17^,^...         1
77000002                                      ^10^,^11^,^3^         1
77000003                                             ^11_c^         7
77000004              ^5^,^3^,^5_18^,^11_18^,^239_18^,^_15^         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372667 entries, 77000000 to 77372666
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   uniqueid          372667 non-null  object
 1   phone             372667 non-null  int64
 2   client_status     372169 non-null  object
 3   assigned_user_id  372169 non-null  object
 4   last_step         372667 non-null  int64
 5   ochered           372667 non-null  int64
 6   call_date         372667 non-null  object
 7   ptv_c             193292 non-null  object
 8   region_c          372667 non-null  int64
dtypes: int64(4), object(5)
memory usage: 25.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372667 entries, 77000000 to 77372666
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   uniqueid          372667 non-null  object
 1   phone             372667 non-null  object
 2   client_status     372169 non-null  object
 3   assigned_user_id  372169 non-null  object
 4   last_step         372667 non-null  object
 5   ochered           372667 non-null  object
 6   call_date         372667 non-null  object
 7   ptv_c             193292 non-null  object
 8   region_c          372667 non-null  object
dtypes: object(9)
memory usage: 25.6+ MB
None

Ушло времени на все файлы: 1123.28 сек.
OK